### ISSUE TITLE
自动打卡

### ISSUE THREAD

**Issue by mmonsterr** [PairZhu/NjtechScript#5]
快开学了，又要每天打卡，能更新一下自动打卡脚本嘛

**Comment by PairZhu** [comment]
目前的脚本仍然可以使用，不需要更新啊

**Comment by PairZhu** [comment]
如果你给脚本正确设置了定时任务之后还是每天收到打卡提醒，请检查你设置的定时任务时间点是否合理。  
建议设置在每天早上8点左右。  
如果设置在凌晨12点附近可能由于服务器和你的系统的时钟存在差异而使得打成了前一天的卡。  
如果设置的时间晚于上午9点，平台会在9点的时候给你发送打卡提醒。
