### ISSUE TITLE
可以考虑加个自动提交过时的健康码

### ISSUE THREAD

**Issue by cautious233** [PairZhu/NjtechScript#6]
老师那里也不在乎你填的什么内容，只管有没有打卡，可以随便找个图片放进去或者自己直接在python运行的时候选择文件上传

**Comment by PairZhu** [comment]
有的老师会检查的，这样做非常不保险，系统就是希望健康码14天重传一次才使健康码会过期的，两周自己打卡一次频率也不高。如果你需要这个功能可以自己修改脚本。

**Comment by dingyang666** [comment]
可以，我去写个吧

**Comment by dingyang666** [comment]
> 有的老师会检查的，这样做非常不保险，系统就是希望健康码14天重传一次才使健康码会过期的，两周自己打卡一次频率也不高。如果你需要这个功能可以自己修改脚本。

有吗，我都是直接传色图的

**Comment by PairZhu** [comment]
> 

有的学院会查，有的狗的不行还检查健康码是不是最新的，每天都要求最新的健康码才行

**Comment by PairZhu** [comment]
> > 有的老师会检查的，这样做非常不保险，系统就是希望健康码14天重传一次才使健康码会过期的，两周自己打卡一次频率也不高。如果你需要这个功能可以自己修改脚本。
> 
> 有吗，我都是直接传色图的

有的学院会查，有的狗的不行还检查健康码是不是最新的，每天都要求最新的健康码才行

**Comment by cautious233** [comment]
> > > 有的老师会检查的，这样做非常不保险，系统就是希望健康码14天重传一次才使健康码会过期的，两周自己打卡一次频率也不高。如果你需要这个功能可以自己修改脚本。
> > 
> > 
> > 有吗，我都是直接传色图的
> 
> 有的学院会查，有的狗的不行还检查健康码是不是最新的，每天都要求最新的健康码才行

这个问题不大，应该写个p健康码的根据时间自己p了提交

**Comment by PairZhu** [comment]
> > > > 有的老师会检查的，这样做非常不保险，系统就是希望健康码14天重传一次才使健康码会过期的，两周自己打卡一次频率也不高。如果你需要这个功能可以自己修改脚本。
> > > 
> > > 
> > > 有吗，我都是直接传色图的
> > 
> > 
> > 有的学院会查，有的狗的不行还检查健康码是不是最新的，每天都要求最新的健康码才行
> 
> 这个问题不大，应该写个p健康码的根据时间自己p了提交

p健康码太刑了，不敢整，被抓到了要负责的，只是自动健康打卡风险不大，而且这增加了部署成本，需要服务器有显示器或者虚拟显示器才能使用

**Comment by PairZhu** [comment]
如果老师不检查健康码可以上传虚空图片（就健康码字段写死为一个不存在的图片名称）我最新的提交里增加了一个参数nocheck，将其设置为True即可
