### ISSUE TITLE
打卡脚本报错

### ISSUE THREAD

**Issue by cautious233** [PairZhu/NjtechScript#8]
ticket = loginRedirectUrl.split('?ticket=')[-1].split('#/')[0]
AttributeError: 'NoneType' object has no attribute 'split'

查了一下好像是url改了还是怎么回事，这情况就我有吗

**Comment by PairZhu** [comment]
因为i南工登录加入了验证码，没办法通过账号密码登录打卡了。后续有空我会改成通过token来打卡，不过这样就需要会抓包。

**Comment by PairZhu** [comment]
已更新
