### ISSUE TITLE
请问有没有一种可能，抓一下验证码，然后用tesseract进行识别呢？

### ISSUE THREAD

**Issue by xwklib** [PairZhu/NjtechScript#9]
这种实现的难度会很大吗

**Comment by PairZhu** [comment]
可以，但是没必要，一是图像识别会有失败的概率还得多次尝试。二是大大增加了部署成本和资源耗费，在一些路由器之类的几乎没有性能的机子上会跑不动，也增加了环境配置的成本。三是不符合我的脚本理念，我认为的脚本就是应该精简，一个脚本只做一件事

**Comment by PairZhu** [comment]
如果这个token会过期的话我会做验证码识别，但是这个token不会失效
